apiVersion: v1
kind: DeploymentConfig
metadata:
  name: simple-service
  namespace: {{PROJECT}}
  labels:
    app: simple-service
spec:
  replicas: 1
  selector:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
      - name: catalog
        image: nexus.esc.yipintsoigroup.com/simple-service:{{TAG_IMAGE}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: nexus